pool:
  vmImage: 'Ubuntu 16.04'
steps:
  - script: |
      npm install
    displayName: "npm install"
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip"
  - task: AzureRmWebAppDeployment@3
    displayName: "Function App Deploy: Super Simple Functions App"
    inputs:
      azureSubscription: "9b301261-f640-4aee-bb8d-ad9fefadeff2"
      appType: functionapp
      WebAppName: "super-simple-functions"
      Package: "$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip"
