pool:
  vmImage: 'Ubuntu 16.04'
steps:
  - script: |
      npm install
    displayName: "npm install"
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip"
  - task: AzureRmWebAppDeployment@3
    displayName: "Function App Deploy: Super Simple Function App"
    inputs:
      azureSubscription: "Microsoft Azure Internal Consumption (8d3519e1-8089-4300-ab0b-bfeda0f9844c)"
      appType: functionapp
      WebAppName: "super-simple-function"
      Package: "$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip"
